os: osx
osx_image: xcode11.3
language: swift
script: xcodebuild clean build test -project VCCompositionWithStoryboards.xcodeproj -scheme "VCCompositionWithStoryboards" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=YES
